name: Build devcontainer image

on:
  push:
    branches: [ main ]
    paths:
      - Dockerfile
      - .github/workflows/build.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        run: |
          OWNER_LC=${{ github.repository_owner }}
          OWNER_LC=${OWNER_LC,,}
          IMAGE=ghcr.io/${OWNER_LC}/is303-python-jupyter:3.12
          echo "Pushing image: $IMAGE"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"
